// packages/soon-i18n/demo/src/app.tsx
import "./app.css";
import SwitchLang from "./components/SwitchLang";
import Content from "./components/Content";
import { useEffect, useState } from "react";
import {
    getLang,
    emitter
} from "./lang";

export function App() {
    const [lang, setLang] = useState(getLang());
    useEffect(() => {
        emitter.on('lang-change',()=>{
            setLang(getLang())
        })
    }, []);

    return (
        <>
            <div className="app card" key={lang}>
                <div>app.tsx</div>
                <SwitchLang />
                <Content />
            </div>
        </>
    );
}

// packages/soon-i18n-vue/demo/src/App.vue
<script setup lang="ts">
import Content from "./components/content.vue";

import LangSwitch from "./components/langSwitch.vue";
</script>

<template>
    <div class="app card">
        <div>app.vue</div>

        <LangSwitch />

        <Content />
    </div>
</template>

<style scoped>
.app {
    background-color: lightblue;

}
</style>
