// packages/soon-i18n-react/demo/src/components/SwitchLang.tsx
import { tLocales, useLang } from "../lang";

const SwitchLang = () => {
    const [lang, setLang] = useLang();
    const t = tLocales({
        zh: {
            lang: "中文",
        },
        en: {
            lang: "English",
        },
    });
    return (
        <div className="lang-switch card">
            <div>child: SwitchLang.tsx</div>
            <button
                onClick={() => {
                    setLang(lang === "en" ? "zh" : "en");
                }}
            >
                {lang} {t("lang")}
            </button>
        </div>
    );
};
export default SwitchLang;

// packages/soon-i18n-svelte/demo/src/components/SwitchLang.svelte
<script lang="ts">
  import { tLocales, lang } from "../lang/index";

  const t = tLocales({
    zh: { lang: "中文" },
    en: { lang: "English" },
  });
</script>

<div class="lang-switch card">
  <div>child: SwitchLang.svelte</div>
  <button
    on:click={() => {
      lang.update((_lang) => (_lang === "en" ? "zh" : "en"));
    }}
  >
    {$lang}
    {$t("lang")}
  </button>
</div>
