// packages/soon-i18n-vue/demo/src/components/content.vue
<template>
  <div class="content card">
    <div>child: content.vue</div>
    <div>{{ t("g_welcome", { name: t("world") }) }}</div>
    <div class="state card">
      <div>{{ t("keepState") }}</div>
      <div>
        {{ t("appleNum") }}:
        <input type="number" v-model="appleNum" min="0" max="10" />
      </div>
      <div>{{ t("own", appleNum) }}</div>
    </div>

    <select>
      <option v-for="item in options">{{ item.label }}</option>
    </select>
    <div>{{ t("eat", 1, 2) }}</div>
    <div>
    <!-- no key err demo -->
    <button @click="showToast">{{ t("show tip") }}</button>
    </div>

  </div>
</template>
<script setup lang="ts">
import { computed } from "vue";
import { showToast, tLocales } from "../lang";
import { ref } from "vue";
import zh_content from "../lang/locales/zh_content";

const appleNum = ref(1);
const t = tLocales({
  zh: zh_content,
  en: () => import("../lang/locales/en_content"),
});
const options = computed(() => [
  {
    label: t("list.apple"),
    value: 0,
  },
  {
    label: t("list.orange"),
    value: 1,
  },
  {
    label: t("list.pear"),
    value: 2,
  },
]);
</script>
<style>
.content {
  background-color: aquamarine;
}
.state {
  background-color: darksalmon;
}
</style>

// packages/soon-i18n/demo/src/components/Content.tsx

import { useState } from "react";
import { showToast, tLocales } from "../lang";
import zh_content from "../lang/locales/zh_content";
import en_content from "../lang/locales/en_content";


export default function Content() {
    const t = tLocales({
        zh: zh_content,
        en: en_content
    })

    const options = [{
        label: t('list.apple'),
        value: 0
    }, {
        label: t('list.orange'),
        value: 1
    }, {
        label: t('list.pear'),
        value: 2
    }]

    const [appleNum, setAppleNum] = useState(1)
    return (
        <div className="content card">
            <div>child: Content.tsx</div>
            <span>{t("g_welcome",{name:t('world')})}</span>

            <div className="state card">
                <div>{t('keepState')}</div>
                <div>
                    {t('appleNum')}:
                    <input type="number" value={appleNum} onChange={e => setAppleNum(Number((e?.target as HTMLInputElement)?.value ?? 0))} min="0" max="10" />
                </div>
                <div>{t("own", appleNum)}</div>
            </div>

            <div>{t('eat', 1, 2)}</div>
            <select>
                {options.map(p => <option v-for="item in options">{p.label}</option>)}

            </select>
            <div>
                {/* no key err demo */}
                <button onClick={showToast}>{t("show tip")}</button>
            </div>
        </div>
    );
}
