// packages/soon-i18n-react/lib/index.js
import { useState as L, useEffect as I, useRef as O } from "react";
import { loadSyncLocales as p, loadLocale as k, flatTreeKey as h, formatObjKey as E } from "soon-i18n-common";
const v = (y, g = {}) => {
  const i = y.fallbacks, K = {}, r = {};
  p(g, r);
  let n = y.lang ?? "", d = 0;
  const a = [], j = () => {
    d++, a.forEach((e) => {
      e(d);
    });
  }, m = (e) => {
    n = e, a.forEach((c) => {
      c(e);
    });
  }, x = () => n, _ = () => {
    const [e, c] = L(n), [l, u] = L(d);
    return I(() => {
      const t = (s) => {
        typeof s == "number" ? u(s) : c(s);
      };
      return a.push(t), () => {
        const s = a.findIndex((f) => f === t);
        a.splice(s, 1);
      };
    }, []), [e, m, l];
  };
  return {
    useLocales: (e = {}) => {
      const [c, l] = L(
        () => {
          const t = {};
          return p(e, t), t;
        }
      ), u = O({});
      return _(), (t, ...s) => {
        const f = {};
        return [n, ...i].reverse().forEach((o) => {
          Object.assign(f, r[o], c[o]);
        }), t in f || [n, ...i].some((o) => {
          if (!c[o])
            return k(
              (b) => {
                l({
                  ...c,
                  [o]: h(b)
                });
              },
              u,
              o,
              e
            ), !0;
          if (!r[o])
            return k(
              (b) => {
                r[o] = h(b), j();
              },
              K,
              o,
              g
            ), !0;
        }), E(f, t, ...s);
      };
    },
    useSoonI18n: _,
    tLocales: (e) => {
      const c = {};
      return p(e, c), (l, ...u) => {
        const t = {};
        return [n, ...i].reverse().forEach((s) => {
          Object.assign(t, r[s], c[s]);
        }), E(t, l, ...u);
      };
    },
    getLang: x,
    setLang: m
  };
};
export {
  v as createI18n
};

// packages/soon-i18n-solid/lib/index.js
import { createSignal as a } from "solid-js";
const x = (e, r) => {
  if (e.indexOf("{") === -1)
    return e;
  let t = e;
  const n = /\{(.*?)\}/g, c = e.match(n);
  return c && c.forEach((o) => {
    if (o.length > 2) {
      const f = o.slice(1, o.length - 1);
      t = t.replace(new RegExp(o, "gm"), r[f] ?? "");
    }
  }), t;
}, u = (e, r = "", t = {}) => {
  for (const n of Object.keys(e)) {
    const c = `${r ? r + "." : ""}${n}`;
    typeof e[n] != "object" ? t[c] = e[n] : u(e[n], c, t);
  }
  return t;
}, E = (e, r, ...t) => {
  if (!e)
    return "";
  const n = e[r] || r;
  return t.length ? typeof n == "function" ? n(...t) : x(n, t[0]) : n;
}, y = (e, r, t, n) => {
  if (n && t && !r[t]) {
    const c = n[t];
    typeof c == "function" ? (r[t] = !0, c().then((o) => {
      e(o.default ?? {});
    }).finally(() => {
      delete r[t];
    })) : e(c ?? {});
  }
}, d = (e, r = {}) => {
  for (const t in e)
    e[t] && typeof e[t] == "object" && (r[t] = u(e[t]));
  return r;
}, L = (e, r = {}) => {
  const [t, n] = a(e.lang ?? ""), [c] = a(e.fallbacks), [o, f] = a(d(r), { equals: !1 }), m = {};
  return {
    tLocales: (p = {}) => {
      const [b, _] = a(d(p), { equals: !1 }), j = {};
      return (h, ...k) => {
        const i = {};
        return [t(), ...c()].reverse().forEach((s) => {
          Object.assign(
            i,
            o()[s],
            b()[s]
          );
        }), h in i || [t(), ...c()].some((s) => {
          if (!b()[s])
            return y(
              (g) => {
                _((l) => (l[s] = u(g), l));
              },
              j,
              s,
              p
            ), !0;
          if (!o()[s])
            return y(
              (g) => {
                f((l) => (l[s] = u(g), l));
              },
              m,
              s,
              r
            ), !0;
        }), E(i, h, ...k);
      };
    },
    lang: t,
    setLang: n
  };
};
export {
  L as createI18n
};
